# Modified from https://github.com/biocore/scikit-bio/
language: python
python:
  - "2.7"
env:
  - NUMPY_VERSION=1.8
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/anaconda/bin:$PATH
  - conda update --yes conda
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip numpy=$NUMPY_VERSION scipy nose pep8 Sphinx coverage scikit-learn
  - source activate env_name
  - pip install coveralls scikit-bio
  - pip install -e . --no-deps
script:
  - nosetests --with-doctest --with-coverage
  - pep8 taxster setup.py
  - taxster show-install-info
  - make -C doc html
after_success:
  - coveralls
